version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
      - backend
    depends_on:
      - pedidos
      - pagos
      - inventarios
      - clientes

  pedidos:
    build: ./pedidos
    networks:
      - backend
    environment:
      - DB_HOST=pedidos_db

  pedidos_db:
    image: mysql:latest
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=pedidos

  pagos:
    build: ./pagos
    networks:
      - backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=pagos_db

  pagos_db:
    image: mysql:latest
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=pagos

  inventarios:
    build: ./inventarios
    networks:
      - backend
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=inventarios_db

  inventarios_db:
    image: mysql:latest
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=inventarios

  clientes:
    build: ./clientes
    networks:
      - backend
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=clientes_db

  clientes_db:
    image: mysql:latest
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=clientes

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

  
networks:
  frontend:
  backend:
  monitoring:
  
volumes:
  grafana-storage: